plugins: []
site_name: Haoyang Ma's homepage
theme:
  # name: material
  name: terminal
# theme: 
#   name: null
#   custom_dir: 'cinder'
nav:
  - Home: index.md
  # - Compiler Correctness: CompilerCorrectness.md
  # - Misc: misc.md
  # - Blog: 
  #   - 2022-10-13: blog/C++ -Memory Management.md
  #   - 2022-10-29: blog/STLC.md
# hide:
#   - Research: papers.md
hide:
  - Blog: blog/blog.md
    # - blog/CompilerCorrectness.md
    # - blog/STLC.md
  - Paitings: play/play.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.arithmatex:
      generic: true
  # - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
    - mermaid2
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  generator: false