plugins: []
site_name: Ma, Haoyang (马昊阳)
theme:
  name: terminal
  features:
    - navigation.side.hide
    - revision.date
nav:
  - Home: index.md
# hide:
#   - Research: papers.md
hide:
  - Blog: blog/blog.md
  - Paitings: play/paintings.md
  - Games: play/games.md
  - Paper: papers.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.arithmatex:
      generic: true
  # - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
    - mermaid2
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  generator: false
extra_css:
  - ./stylesheets/extra.css