plugins: []
site_name: Haoyang Ma's homepage
theme: 
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Compiler Correctness: CompilerCorrectness.md
  # - Misc: misc.md
  # - Blog: 
  #   - 2022-10-13: blog/C++ -Memory Management.md
  #   - 2022-10-29: blog/STLC.md
# hide:
#   - Research papers: papers.md
extra_css: [extra.css]
google_analytics: ['UA-36723568-3', 'mkdocs.org']
# theme: 
#   name: material