name: build
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: install mkdocs-material
        run: pip install mkdocs-material
      - name: install mkdocs-terminal
        run: pip install mkdocs-terminal
      - name: install mermaid
        run: pip install mkdocs-mermaid2-plugin
      - name: build with mkdocs
        run: mkdocs build
      - name: check the site
        run: ls ./site
      - name: push
        run: |
          cd site
          pwd
          git init
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "refresh website"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/haoyang9804/haoyang9804.github.io master:gh-pages -f
