name: build
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: install mkdocs
        run: pip install mkdocs
      - name: build with mkdocs
        run: mkdocs build
      - name: check the site
        run: ls ./site 
      - name: Commit local files
        run: |
          cd site
          pwd
          git init
          git config --local user.email "haoyang9804"
          git config --local user.name "haoyanghkust@gmail.com"
          git add .
          git commit -m "refresh website"
      - name: set remote repo
        run: |
          git remote set-url origin https://x-access-token:${{ env.MY_GITHUB_TOKEN }}@github.com/haoyang9804/haoyang9804.github.io
          git remote -v
      - name: push gh-pages
        run: |
          git push origin master:gh-pages
#         uses: ad-m/github-push-action@master
#         with:
#           repository: haoyang9804/test
#           github_token: ${{ secrets.MY_GITHUB_TOKEN }}
#           branch: gh-pages
