name: build
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: install mkdocs
        run: pip install mkdocs
      - name: build with mkdocs
        run: mkdocs build
      - name: check the site
        run: ls ./site
      - name: config
        run: |
          cd site
          pwd
          git init
          git config user.name haoyang9804
          git config user.email haoyanghkust@gmail.com
          git add . && git commit -m "refresh website"
          git push https://${{ secrets.MY_GITHUB_TOKEN }}/haoyang9804/haoyang9804.github.io.git -f master:gh-pages
#       - name: test MY_GITHUB_TOKEN
#         run: echo ${{ secrets.MY_GITHUB_TOKEN }}
#       - name: push gh-pages
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.MY_GITHUB_TOKEN }}
#           branch: gh-pages
