name: Update Download Count
on:
  push:
    branches:
      - master
# on:
#   schedule:
#     - cron: '0 0 * * *'  # Runs daily at midnight UTC
#   workflow_dispatch:  # Allows manual triggering

jobs:
  update-downloads:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run download count script
      run: |
          python fetch_fm_model_downloads.py
          python fetch_erwin_downloads.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update download count badge"
        git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/haoyang9804/haoyang9804.github.io master:master -f
